[package]
name = "ws-com-framework"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = {version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bincode = "1.2.1"
warp = "0.3"
uuid = {version = "0.8", features = ["serde", "v4"]}