[package]
name = "ws-com-framework"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = {version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bincode = "1.2.1"
warp = "0.3" #TODO this dependency is *enourmous* and we really only need it to enable conversions to its ws::Message type...
uuid = {version = "0.8", features = ["serde", "v4"]}
futures="0.3.16"
async-trait = "0.1.51"
tokio = { version = "1", features = ["full"] }
macros = { path = "./macros" } #Eventually this will be split off into it's own crate (workspace/github repo)