name: Build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build & Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install -y build-essential protobuf-compiler
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --all